-- ============================================================
-- 均线多头排列 选股特征 (A股全市场, 聚源 QT_DAILYQUOTE)
-- 适用库: ZBJYDB (service JYDBTEST, Oracle 11g)
-- 时间语义: T0 = 最新交易日收盘; 仅用 T0 及历史数据, 无未来泄露
-- 规则:
--   1) T0 与 T-1 均满足 MA5>MA10>MA20>MA60>MA120>MA250 (多头排列)
--   2) 每条均线均向上: T0.MA > T-1.MA
-- 说明:
--   - 均线用"交易日"窗口(ROWS BETWEEN n-1 PRECEDING), 非自然日
--   - rn>=250 保证 MA250 是真实 250 日均值(排除次新股失真)
--   - (T0-PREV_DAY)<=7 保证 T-1 是最近一个交易日(规避长期停牌被误当"昨天")
-- ============================================================

WITH vd AS (
    -- 最新交易日 T0
    SELECT MAX(TRADINGDAY) AS t0 FROM ZBJYDB.QT_DAILYQUOTE
),
ma AS (
    -- 逐只证券计算 6 条均线 + 行号(用于历史长度过滤)
    SELECT
        D.INNERCODE,
        SM.SECUCODE,
        SM.CHINAME   AS SECNAME,
        D.TRADINGDAY,
        D.CLOSEPRICE,
        ROW_NUMBER() OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY) AS rn,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS MA5,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS MA10,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS MA20,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS MA60,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS MA250
    FROM ZBJYDB.QT_DAILYQUOTE D
    JOIN ZBJYDB.SECUMAIN SM ON D.INNERCODE = SM.INNERCODE
    WHERE SUBSTR(SM.SECUCODE,1,2) IN ('60','68','00','30')   -- 沪深A股代码区间(主板/科创板/创业板)
      AND SM.SECUCATEGORY = 1                                 -- 证券类别=股票(A股), 排除指数(4)/基金(8)/债券(6)
      AND D.CLOSEPRICE IS NOT NULL
      AND D.TRADINGDAY <= (SELECT t0 FROM vd)
      AND D.TRADINGDAY >= (SELECT t0 FROM vd) - 400           -- 下界: 留出 MA250 所需约250交易日窗口
),
lagged AS (
    -- 取 T-1 (上一交易日) 的均线值, 以及上一交易日日期
    SELECT
        m.*,
        LAG(MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA5,
        LAG(MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA10,
        LAG(MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA20,
        LAG(MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA60,
        LAG(MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA120,
        LAG(MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA250,
        LAG(TRADINGDAY) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_DAY
    FROM ma m
)
SELECT
    SECUCODE,
    SECNAME,
    TO_CHAR(TRADINGDAY,'YYYY-MM-DD') AS T0,
    ROUND(CLOSEPRICE,3) AS CLOSEPRICE,
    ROUND(MA5,3)    AS MA5,
    ROUND(MA10,3)   AS MA10,
    ROUND(MA20,3)   AS MA20,
    ROUND(MA60,3)   AS MA60,
    ROUND(MA120,3)  AS MA120,
    ROUND(MA250,3)  AS MA250,
    ROUND(MA5  - PREV_MA5,4)  AS D_MA5,
    ROUND(MA10 - PREV_MA10,4) AS D_MA10,
    ROUND(MA20 - PREV_MA20,4) AS D_MA20,
    ROUND(MA60 - PREV_MA60,4) AS D_MA60,
    ROUND(MA120- PREV_MA120,4) AS D_MA120,
    ROUND(MA250- PREV_MA250,4) AS D_MA250
FROM lagged, vd
WHERE TRADINGDAY = vd.t0
  AND rn >= 250                                              -- 足够历史, MA250 为真实均值
  AND (vd.t0 - PREV_DAY) <= 7                               -- T-1 是最近交易日(防停牌失真)
  -- T0 多头排列
  AND MA5   > MA10 AND MA10  > MA20 AND MA20  > MA60 AND MA60 > MA120 AND MA120 > MA250
  -- T-1 多头排列
  AND PREV_MA5  > PREV_MA10 AND PREV_MA10 > PREV_MA20 AND PREV_MA20 > PREV_MA60 AND PREV_MA60 > PREV_MA120 AND PREV_MA120 > PREV_MA250
  -- 各均线向上 (T0 > T-1)
  AND MA5   > PREV_MA5   AND MA10  > PREV_MA10 AND MA20  > PREV_MA20
  AND MA60  > PREV_MA60  AND MA120 > PREV_MA120 AND MA250 > PREV_MA250
ORDER BY SECUCODE
;
