-- ============================================================
-- A股全市场最近 200 个 A股交易日「全量 9 大核心策略因子 + 均线系统」特征矩阵
-- 适用库: ZBJYDB (service JYDBTEST, Oracle 11g)
-- 生产主口径: CS_STOCKADJPERFORMANCE (ADJUSTINGMETHOD=1, ADJUSTINGSTANDARD=1 前复权精确复权)
-- 成交额合并: QT_DAILYQUOTE (60/00/30) UNION ALL LC_STIBDAILYQUOTE (68科创板)
-- 股票范围: SUBSTR(SECUCODE,1,2) IN ('60','68','00','30') AND SECUCATEGORY = 1
-- 日历与连续性: 基于 QT_TRADINGDAYNEW 市场交易日序号 MARKET_TD_SEQ 与真实上市交易日数 LISTING_TDAYS
-- 严格停牌强约束: 序号等差连续 + 窗口内 SUM(IS_TRADING) = 窗口天数 (双重杜绝停牌占位行)
-- 严谨有效交易日新高 (纯有效行情序列 CTE 计算 WIN_HIGH_250 / WIN_HIGH_500，严格匹配 Python 模型)
-- 严格遵循原始需求: LISTING_TDAYS > 500 门槛 (次新股突破前高降级归入 250日新高)
-- ============================================================

WITH ashare_stocks AS (
    SELECT 
        INNERCODE, 
        SECUCODE, 
        COALESCE(SECUABBR, CHINAME) AS SECNAME,
        LISTEDDATE
    FROM ZBJYDB.SECUMAIN
    WHERE SUBSTR(SECUCODE,1,2) IN ('60','68','00','30')
      AND SECUCATEGORY = 1
),
market_calendar AS (
    SELECT 
        TRADINGDATE,
        ROW_NUMBER() OVER (ORDER BY TRADINGDATE ASC) AS MARKET_TD_SEQ
    FROM ZBJYDB.QT_TRADINGDAYNEW
    WHERE SECUMARKET = 83 AND IFTRADINGDAY = 1
),
ashare_dates AS (
    SELECT DISTINCT P.TRADINGDAY
    FROM ZBJYDB.CS_STOCKADJPERFORMANCE P
    JOIN ashare_stocks S ON P.INNERCODE = S.INNERCODE
    WHERE P.ADJUSTINGMETHOD = 1 AND P.ADJUSTINGSTANDARD = 1
    ORDER BY P.TRADINGDAY DESC
),
recent_200_days AS (
    SELECT TRADINGDAY FROM (
        SELECT TRADINGDAY FROM ashare_dates
    ) WHERE ROWNUM <= 200
),
min_max_dates AS (
    SELECT MIN(TRADINGDAY) AS min_t, MAX(TRADINGDAY) AS max_t FROM recent_200_days
),
all_market_quotes AS (
    SELECT INNERCODE, TRADINGDAY, CLOSEPRICE, TURNOVERVALUE FROM ZBJYDB.QT_DAILYQUOTE
    UNION ALL
    SELECT INNERCODE, TRADINGDAY, CLOSEPRICE, TURNOVERVALUE FROM ZBJYDB.LC_STIBDAILYQUOTE
),
raw_base AS (
    SELECT 
        P.INNERCODE,
        P.TRADINGDAY,
        P.ADJOPENPRICE,
        P.ADJHIGHPRICE,
        P.ADJLOWPRICE,
        P.ADJCLOSEPRICE,
        COALESCE(Q.CLOSEPRICE, P.ADJCLOSEPRICE) AS RAW_CLOSEPRICE,
        COALESCE(Q.TURNOVERVALUE, 0)           AS TURNOVERVALUE,
        CASE WHEN COALESCE(Q.TURNOVERVALUE, 0) > 0 THEN 1 ELSE 0 END AS IS_TRADING
    FROM ZBJYDB.CS_STOCKADJPERFORMANCE P
    JOIN ashare_stocks S ON P.INNERCODE = S.INNERCODE
    LEFT JOIN all_market_quotes Q
      ON P.INNERCODE = Q.INNERCODE AND P.TRADINGDAY = Q.TRADINGDAY
    WHERE P.ADJUSTINGMETHOD = 1 
      AND P.ADJUSTINGSTANDARD = 1
      AND P.ADJCLOSEPRICE IS NOT NULL
),
-- 纯有效正常交易日序列 (独立计算过去 250 / 500 个真实有效交易日最高价，不受停牌占位行干扰)
trading_quotes_only AS (
    SELECT
        INNERCODE,
        TRADINGDAY,
        ROW_NUMBER() OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ASC) AS TRADING_DAY_RN,
        MAX(ADJHIGHPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS MAX_ALL_PRIOR,
        MAX(ADJHIGHPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 500 PRECEDING AND 1 PRECEDING)       AS WIN_HIGH_500,
        MAX(ADJHIGHPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 250 PRECEDING AND 1 PRECEDING)       AS WIN_HIGH_250
    FROM raw_base
    WHERE IS_TRADING = 1
),
enriched_base AS (
    SELECT 
        b.INNERCODE,
        s.SECUCODE,
        s.SECNAME,
        s.LISTEDDATE,
        b.TRADINGDAY,
        b.ADJOPENPRICE,
        b.ADJHIGHPRICE,
        b.ADJLOWPRICE,
        b.ADJCLOSEPRICE,
        b.RAW_CLOSEPRICE,
        b.TURNOVERVALUE,
        b.IS_TRADING,
        c.MARKET_TD_SEQ,
        CASE WHEN cl.MARKET_TD_SEQ IS NOT NULL AND c.MARKET_TD_SEQ >= cl.MARKET_TD_SEQ 
             THEN (c.MARKET_TD_SEQ - cl.MARKET_TD_SEQ + 1)
             ELSE NULL END AS LISTING_TDAYS,
        CASE WHEN b.ADJCLOSEPRICE > b.ADJOPENPRICE AND b.IS_TRADING = 1 THEN 1 ELSE 0 END AS IS_RED,
        CASE WHEN b.ADJCLOSEPRICE < b.ADJOPENPRICE AND b.IS_TRADING = 1 THEN 1 ELSE 0 END AS IS_GREEN,
        t.TRADING_DAY_RN,
        t.MAX_ALL_PRIOR,
        t.WIN_HIGH_500,
        t.WIN_HIGH_250
    FROM raw_base b
    JOIN ashare_stocks s ON b.INNERCODE = s.INNERCODE
    JOIN market_calendar c ON b.TRADINGDAY = c.TRADINGDATE
    LEFT JOIN market_calendar cl ON s.LISTEDDATE = cl.TRADINGDATE
    LEFT JOIN trading_quotes_only t ON b.INNERCODE = t.INNERCODE AND b.TRADINGDAY = t.TRADINGDAY
),
window_stats AS (
    SELECT
        d.*,
        ROW_NUMBER() OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS rn,

        -- 前复权均线 (MA5..MA377)
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS MA5,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS MA10,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS MA20,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS MA60,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS MA250,
        AVG(ADJCLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 376 PRECEDING AND CURRENT ROW) AS MA377,

        -- 窗口内有效正常交易日计数 (强约束无停牌)
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   1 PRECEDING AND CURRENT ROW) AS TRADING_CNT_2,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS TRADING_CNT_5,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   5 PRECEDING AND CURRENT ROW) AS TRADING_CNT_6,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   3 PRECEDING AND CURRENT ROW) AS TRADING_CNT_4,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  15 PRECEDING AND CURRENT ROW) AS TRADING_CNT_16,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 179 PRECEDING AND CURRENT ROW) AS TRADING_CNT_180,
        SUM(IS_TRADING) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 181 PRECEDING AND CURRENT ROW) AS TRADING_CNT_182,

        -- HL+5R 窗口
        MIN(ADJLOWPRICE)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW)   AS RECENT_LOW_10,
        MAX(ADJHIGHPRICE)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 169 PRECEDING AND CURRENT ROW) AS WIN_HIGH_170,
        MIN(ADJLOWPRICE)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW)  AS WIN_LOW_30,

        -- HL+AMO 窗口
        MAX(ADJHIGHPRICE)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 179 PRECEDING AND CURRENT ROW) AS WIN_HIGH_180,

        -- AMO 窗口
        MAX(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 14 PRECEDING AND CURRENT ROW) AS WIN_MAX_15,
        AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)  AS WIN_AVG_5,
        AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW)  AS WIN_AVG_10,
        AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 14 PRECEDING AND CURRENT ROW) AS WIN_AVG_15
    FROM enriched_base d
),
lagged AS (
    SELECT
        w.*,
        LAG(MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA5,
        LAG(MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA10,
        LAG(MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA20,
        LAG(MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA60,
        LAG(MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA120,
        LAG(MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA250,
        LAG(MA377) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA377,

        LAG(TRADINGDAY, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_DAY,
        LAG(MARKET_TD_SEQ, 1)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_1,
        LAG(MARKET_TD_SEQ, 3)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_3,
        LAG(MARKET_TD_SEQ, 4)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_4,
        LAG(MARKET_TD_SEQ, 5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_5,
        LAG(MARKET_TD_SEQ, 15)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_15,
        LAG(MARKET_TD_SEQ, 179) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_179,
        LAG(MARKET_TD_SEQ, 181) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_SEQ_181,

        LAG(IS_RED, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T1,
        LAG(IS_RED, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T2,
        LAG(IS_RED, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T3,
        LAG(IS_RED, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T4,
        LAG(IS_GREEN, 5) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS GREEN_T5,

        LAG(ADJOPENPRICE, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS ADJ_OPEN_T4,
        LAG(WIN_HIGH_170, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_HIGH_170,
        LAG(WIN_LOW_30, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_LOW_30,

        LAG(TURNOVERVALUE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AMT_1,
        LAG(WIN_MAX_15, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS MAX_15,
        LAG(WIN_AVG_5, 1)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_5,
        LAG(WIN_AVG_10, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_10,
        LAG(WIN_AVG_15, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_15,
        LAG(ADJCLOSEPRICE, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS ADJ_CLOSE_T10,

        LAG(ADJCLOSEPRICE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS ADJ_CLOSE_T1,
        LAG(WIN_HIGH_180, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_HIGH_180,

        CASE WHEN MA250 > 0 THEN (ADJCLOSEPRICE / MA250 - 1.0) END AS DIST_250_T0,
        CASE WHEN LAG(MA250, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA250, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_250_T1,
        CASE WHEN LAG(MA250, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA250, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_250_T2,
        CASE WHEN LAG(MA250, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA250, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_250_T3,

        CASE WHEN MA377 > 0 THEN (ADJCLOSEPRICE / MA377 - 1.0) END AS DIST_377_T0,
        CASE WHEN LAG(MA377, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA377, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_377_T1,
        CASE WHEN LAG(MA377, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA377, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_377_T2,
        CASE WHEN LAG(MA377, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) > 0 
             THEN (LAG(ADJCLOSEPRICE, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) / LAG(MA377, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) - 1.0) END AS DIST_377_T3
    FROM window_stats w
),
calculated AS (
    SELECT
        l.*,
        -- 严格 5 市场交易日连续无停牌且 5 日连红 (TRADING_CNT_5=5 且等差)
        CASE WHEN IS_RED = 1 AND RED_T1 = 1 AND RED_T2 = 1 AND RED_T3 = 1 AND RED_T4 = 1 
              AND (MARKET_TD_SEQ - PREV_SEQ_4) = 4 AND TRADING_CNT_5 = 5
             THEN 1 ELSE 0 END AS RED_5_STRICT,

        -- 严格 6 市场交易日连续无停牌
        CASE WHEN (MARKET_TD_SEQ - PREV_SEQ_5) = 5 AND TRADING_CNT_6 = 6 THEN 1 ELSE 0 END AS IS_CONSEC_6D,

        -- 严格 4 市场交易日连续无停牌
        CASE WHEN (MARKET_TD_SEQ - PREV_SEQ_3) = 3 AND TRADING_CNT_4 = 4 THEN 1 ELSE 0 END AS IS_CONSEC_4D,

        -- 严格长周期无停牌 (序号等差 + 有效交易日满额)
        CASE WHEN (MARKET_TD_SEQ - PREV_SEQ_15) = 15   AND TRADING_CNT_16 = 16   THEN 1 ELSE 0 END AS IS_CONSEC_16D,
        CASE WHEN (MARKET_TD_SEQ - PREV_SEQ_179) = 179 AND TRADING_CNT_180 = 180 THEN 1 ELSE 0 END AS IS_CONSEC_180D,
        CASE WHEN (MARKET_TD_SEQ - PREV_SEQ_181) = 181 AND TRADING_CNT_182 = 182 THEN 1 ELSE 0 END AS IS_CONSEC_182D,

        CASE WHEN PRIOR_HIGH_170 > 0.001 THEN 1.0 - RECENT_LOW_10 / PRIOR_HIGH_170 ELSE NULL END AS DRAWDOWN_180,
        CASE WHEN PRIOR_LOW_30 > 0.001 THEN RECENT_LOW_10 / PRIOR_LOW_30 - 1.0 ELSE NULL END AS LOW_REBOUND_30,
        CASE WHEN ADJ_OPEN_T4 > 0.001 THEN ADJCLOSEPRICE / ADJ_OPEN_T4 - 1.0 ELSE NULL END AS FIVE_DAY_GAIN,
        CASE WHEN ADJ_CLOSE_T10 > 0.001 THEN ADJCLOSEPRICE / ADJ_CLOSE_T10 - 1.0 ELSE NULL END AS RETURN_10,
        CASE WHEN PRIOR_HIGH_180 > 0.001 THEN 1.0 - ADJ_CLOSE_T1 / PRIOR_HIGH_180 ELSE NULL END AS PREV_DRAWDOWN_180,

        CASE WHEN (IS_RED = 1 OR RED_T1 = 1 OR RED_T2 = 1 OR RED_T3 = 1) THEN 1 ELSE 0 END AS HAS_RED_4D
    FROM lagged l
),
factored AS (
    SELECT
        c.*,
        -- 1. FACTOR_HL_5R (底部五连阳, 180日无任何停牌且T-5为阴线)
        CASE WHEN rn >= 180 AND IS_CONSEC_180D = 1 AND DRAWDOWN_180 IS NOT NULL AND DRAWDOWN_180 > 0.25 AND LOW_REBOUND_30 IS NOT NULL AND LOW_REBOUND_30 < 0.10 AND RED_5_STRICT = 1 AND GREEN_T5 = 1 AND FIVE_DAY_GAIN IS NOT NULL AND FIVE_DAY_GAIN < 0.13 THEN 1 ELSE 0 END AS FACTOR_HL_5R,
        
        -- 2. FACTOR_5R (五连阳，排除 HL+5R, 6日无任何停牌)
        CASE WHEN rn >= 6 AND RED_5_STRICT = 1 AND GREEN_T5 = 1 AND IS_CONSEC_6D = 1
              AND NOT (rn >= 180 AND IS_CONSEC_180D = 1 AND DRAWDOWN_180 IS NOT NULL AND DRAWDOWN_180 > 0.25 AND LOW_REBOUND_30 IS NOT NULL AND LOW_REBOUND_30 < 0.10 AND RED_5_STRICT = 1 AND FIVE_DAY_GAIN IS NOT NULL AND FIVE_DAY_GAIN < 0.13) 
             THEN 1 ELSE 0 END AS FACTOR_5R,

        -- 3. 覆盖期新高 / 500日新高 / 250日新高 (严谨求真口径: 严格要求样本深度，剔除假阳性)
        CASE WHEN IS_TRADING = 1 AND LISTING_TDAYS IS NOT NULL AND LISTING_TDAYS > 500 
              AND TRADING_DAY_RN >= 501 AND ADJHIGHPRICE > MAX_ALL_PRIOR 
             THEN 1 ELSE 0 END AS FACTOR_HIGH_ALL,
        CASE WHEN IS_TRADING = 1 AND LISTING_TDAYS IS NOT NULL AND LISTING_TDAYS > 500 
              AND TRADING_DAY_RN >= 501 AND ADJHIGHPRICE > WIN_HIGH_500
             THEN 1 ELSE 0 END AS FACTOR_HIGH_500,
        CASE WHEN IS_TRADING = 1 AND LISTING_TDAYS IS NOT NULL AND LISTING_TDAYS > 250 
              AND TRADING_DAY_RN >= 251 AND ADJHIGHPRICE > WIN_HIGH_250
             THEN 1 ELSE 0 END AS FACTOR_HIGH_250,

        -- 4. FACTOR_AMO (放量突破, 16日无任何停牌)
        CASE WHEN rn >= 16 AND IS_CONSEC_16D = 1 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 
              AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 
              AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 
              AND IS_RED = 1 AND RETURN_10 IS NOT NULL AND RETURN_10 < 0.50 THEN 1 ELSE 0 END AS FACTOR_AMO,

        -- 5. FACTOR_HL_AMO (低位放量, 182日无任何停牌)
        CASE WHEN rn >= 182 AND IS_CONSEC_182D = 1 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 
              AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 
              AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 
              AND IS_RED = 1 AND RETURN_10 IS NOT NULL AND RETURN_10 < 0.50 AND PREV_DRAWDOWN_180 IS NOT NULL AND PREV_DRAWDOWN_180 > 0.25 THEN 1 ELSE 0 END AS FACTOR_HL_AMO,

        -- 6. FACTOR_MA250_SUPPORT & FACTOR_MA377_SUPPORT (4日无任何停牌)
        CASE WHEN rn >= 253 AND HAS_RED_4D = 1 AND IS_CONSEC_4D = 1
              AND DIST_250_T0 BETWEEN -0.02 AND 0.07
              AND DIST_250_T1 BETWEEN -0.02 AND 0.07
              AND DIST_250_T2 BETWEEN -0.02 AND 0.07
              AND DIST_250_T3 BETWEEN -0.02 AND 0.07
             THEN 1 ELSE 0 END AS FACTOR_MA250_SUPPORT,

        CASE WHEN rn >= 380 AND HAS_RED_4D = 1 AND IS_CONSEC_4D = 1
              AND DIST_377_T0 BETWEEN -0.02 AND 0.07
              AND DIST_377_T1 BETWEEN -0.02 AND 0.07
              AND DIST_377_T2 BETWEEN -0.02 AND 0.07
              AND DIST_377_T3 BETWEEN -0.02 AND 0.07
             THEN 1 ELSE 0 END AS FACTOR_MA377_SUPPORT
    FROM calculated c
)
SELECT
    SECUCODE,
    SECNAME,
    TO_CHAR(TRADINGDAY, 'YYYY-MM-DD') AS T0,
    TO_CHAR(PREV_DAY, 'YYYY-MM-DD')   AS PREV_DAY,
    (MARKET_TD_SEQ - PREV_SEQ_1)     AS DAY_GAP,
    rn                              AS HISTORY_DAYS,
    ROUND(RAW_CLOSEPRICE, 3)        AS CLOSEPRICE,
    ROUND(ADJCLOSEPRICE, 3)         AS ADJ_CLOSE,
    1.0000                          AS ADJUSTINGFACTOR,
    ROUND(TURNOVERVALUE, 0)         AS TURNOVERVALUE,

    -- 均线系统 (前复权精确主口径)
    ROUND(CASE WHEN rn>=5   THEN MA5   END, 3) AS MA5,
    ROUND(CASE WHEN rn>=10  THEN MA10  END, 3) AS MA10,
    ROUND(CASE WHEN rn>=20  THEN MA20  END, 3) AS MA20,
    ROUND(CASE WHEN rn>=60  THEN MA60  END, 3) AS MA60,
    ROUND(CASE WHEN rn>=120 THEN MA120 END, 3) AS MA120,
    ROUND(CASE WHEN rn>=250 THEN MA250 END, 3) AS MA250,
    ROUND(CASE WHEN rn>=377 THEN MA377 END, 3) AS MA377,

    ROUND(CASE WHEN rn>=6   THEN PREV_MA5   END, 3) AS PREV_MA5,
    ROUND(CASE WHEN rn>=11  THEN PREV_MA10  END, 3) AS PREV_MA10,
    ROUND(CASE WHEN rn>=21  THEN PREV_MA20  END, 3) AS PREV_MA20,
    ROUND(CASE WHEN rn>=61  THEN PREV_MA60  END, 3) AS PREV_MA60,
    ROUND(CASE WHEN rn>=121 THEN PREV_MA120 END, 3) AS PREV_MA120,
    ROUND(CASE WHEN rn>=251 THEN PREV_MA250 END, 3) AS PREV_MA250,
    ROUND(CASE WHEN rn>=378 THEN PREV_MA377 END, 3) AS PREV_MA377,

    -- 均线超级多头排列 (LABEL: 必须为正常交易日 IS_TRADING=1 且满足双日六线排列与上升，杜绝停牌复牌首日均线冻结误判)
    CASE WHEN rn>=250 AND IS_TRADING = 1 AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250 THEN 1 ELSE 0 END AS ALIGN_T0,
    CASE WHEN rn>=251 AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60 AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250 THEN 1 ELSE 0 END AS ALIGN_T1,
    CASE WHEN rn>=251 AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20 AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250 THEN 1 ELSE 0 END AS ALL_UP,
    CASE WHEN rn>=251 AND IS_TRADING = 1 AND TRADING_CNT_2 = 2 AND (MARKET_TD_SEQ - PREV_SEQ_1) = 1
              AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
              AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60 AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
              AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20 AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
         THEN 1 ELSE 0 END AS LABEL,

    -- ===== 全量 9 大核心策略因子标签 =====
    FACTOR_HL_5R,
    FACTOR_5R,
    FACTOR_HIGH_ALL,
    FACTOR_HIGH_500,
    FACTOR_HIGH_250,
    FACTOR_HL_AMO,
    FACTOR_AMO,
    FACTOR_MA377_SUPPORT,
    FACTOR_MA250_SUPPORT,

    -- 衍生复合分类
    CASE WHEN FACTOR_HIGH_ALL = 1 THEN 'ALL_TIME'
         WHEN FACTOR_HIGH_500 = 1 THEN 'D500'
         WHEN FACTOR_HIGH_250 = 1 THEN 'D250'
         ELSE 'NONE' END AS HIGH_TYPE,

    CASE WHEN FACTOR_MA250_SUPPORT = 1 AND FACTOR_MA377_SUPPORT = 1 THEN 'BOTH'
         WHEN FACTOR_MA377_SUPPORT = 1 THEN 'MA377'
         WHEN FACTOR_MA250_SUPPORT = 1 THEN 'MA250'
         ELSE 'NONE' END AS MA_SUPPORT_TYPE,

    -- PRIMARY_FACTOR 单标签综合优先级
    CASE WHEN FACTOR_HL_5R = 1 THEN 'HL_5R'
         WHEN FACTOR_5R = 1 THEN '5R'
         WHEN FACTOR_HIGH_ALL = 1 THEN 'HIGH_ALL'
         WHEN FACTOR_HIGH_500 = 1 THEN 'HIGH_500'
         WHEN FACTOR_HIGH_250 = 1 THEN 'HIGH_250'
         WHEN FACTOR_HL_AMO = 1 THEN 'HL_AMO'
         WHEN FACTOR_AMO = 1 THEN 'AMO'
         WHEN FACTOR_MA377_SUPPORT = 1 THEN 'MA377_SUPPORT'
         WHEN FACTOR_MA250_SUPPORT = 1 THEN 'MA250_SUPPORT'
         ELSE 'NONE' END AS PRIMARY_FACTOR,

    -- 详细量化指标输出
    ROUND(DRAWDOWN_180 * 100, 2)       AS DRAWDOWN_180_PCT,
    ROUND(LOW_REBOUND_30 * 100, 2)     AS LOW_REBOUND_30_PCT,
    ROUND(FIVE_DAY_GAIN * 100, 2)      AS FIVE_DAY_GAIN_PCT,
    ROUND(RETURN_10 * 100, 2)          AS RETURN_10_PCT,
    ROUND(PREV_DRAWDOWN_180 * 100, 2)  AS PREV_DRAWDOWN_180_PCT,
    ROUND(TURNOVERVALUE / NULLIF(AMT_1, 0), 2)  AS AMT_RATIO_PREV,
    ROUND(TURNOVERVALUE / NULLIF(AVG_5, 0), 2)  AS AMT_RATIO_MA5,
    ROUND(TURNOVERVALUE / NULLIF(AVG_10, 0), 2) AS AMT_RATIO_MA10,
    ROUND(TURNOVERVALUE / NULLIF(AVG_15, 0), 2) AS AMT_RATIO_MA15,
    ROUND(TURNOVERVALUE / NULLIF(MAX_15, 0), 2) AS AMT_RATIO_MAX15,
    ROUND(DIST_250_T0 * 100, 2)        AS DIST_MA250_PCT,
    ROUND(DIST_377_T0 * 100, 2)        AS DIST_MA377_PCT
FROM (SELECT /*+ NO_MERGE NO_PUSH_PRED */ * FROM factored) fx, min_max_dates m
WHERE fx.TRADINGDAY >= m.min_t
ORDER BY fx.TRADINGDAY DESC, fx.SECUCODE ASC
