-- ============================================================
-- A股全市场「均线多头排列」特征矩阵 + 标签 (聚源 QT_DAILYQUOTE)
-- 适用库: ZBJYDB (service JYDBTEST, Oracle 11g)
-- 时间语义: T0 = 最新交易日收盘; 仅用 T0 及历史数据, 无未来泄露
-- 产出: 每只A股一行(T0快照), 各均线(T0/T-1)为特征值, LABEL 为标签
--   1) T0 与 T-1 均满足 MA5>MA10>MA20>MA60>MA120>MA250 (多头排列)
--   2) 每条均线均向上: T0.MA > T-1.MA
-- 工程处理:
--   - 均线用"交易日"窗口(ROWS BETWEEN n-1 PRECEDING), 非自然日
--   - MA列用 rn>=n 才输出数值, 否则 NULL(次新股不满足历史长度)
--   - DAY_GAP=(T0-PREV_DAY); LABEL 要求 DAY_GAP<=7(防长期停牌被误当"昨天")
-- 列说明:
--   SECUCODE/SECNAME      证券代码/名称
--   T0 / PREV_DAY         当日/上一交易日
--   DAY_GAP / HISTORY_DAYS 间隔天数 / 上市以来交易日数(rn)
--   MA5..MA250            T0 各周期均线(特征)
--   PREV_MA5..PREV_MA250  T-1 各周期均线(特征/用于斜率)
--   ALIGN_T0/ALIGN_T1     当日/昨日 多头排列标记(0/1)
--   ALL_UP                所有均线 T0>T-1 向上标记(0/1)
--   LABEL                 综合标签: 满足完整规则=1, 否则=0
-- ============================================================

WITH vd AS (
    -- 最新交易日 T0
    SELECT MAX(TRADINGDAY) AS t0 FROM ZBJYDB.QT_DAILYQUOTE
),
ma AS (
    -- 逐只证券计算 6 条均线 + 行号(历史长度)
    SELECT
        D.INNERCODE,
        SM.SECUCODE,
        COALESCE(SM.SECUABBR, SM.CHINAME) AS SECNAME,
        D.TRADINGDAY,
        D.CLOSEPRICE,
        ROW_NUMBER() OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY) AS rn,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS MA5,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS MA10,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS MA20,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS MA60,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120,
        AVG(D.CLOSEPRICE) OVER (PARTITION BY D.INNERCODE ORDER BY D.TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS MA250
    FROM ZBJYDB.QT_DAILYQUOTE D
    JOIN ZBJYDB.SECUMAIN SM ON D.INNERCODE = SM.INNERCODE
    WHERE SUBSTR(SM.SECUCODE,1,2) IN ('60','68','00','30')   -- 沪深A股代码区间(主板/科创板/创业板)
      AND SM.SECUCATEGORY = 1                                 -- 证券类别=股票(A股), 排除指数(4)/基金(8)/债券(6)
      AND D.CLOSEPRICE IS NOT NULL
      AND D.TRADINGDAY <= (SELECT t0 FROM vd)
      AND D.TRADINGDAY >= (SELECT t0 FROM vd) - 400           -- 下界: 留出 MA250 所需约250交易日窗口
),
lagged AS (
    -- 取 T-1 (上一交易日) 的均线值 与 上一交易日日期
    SELECT
        m.*,
        LAG(MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA5,
        LAG(MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA10,
        LAG(MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA20,
        LAG(MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA60,
        LAG(MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA120,
        LAG(MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA250,
        LAG(TRADINGDAY) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_DAY
    FROM ma m
)
SELECT
    SECUCODE,
    SECNAME,
    TO_CHAR(TRADINGDAY,'YYYY-MM-DD') AS T0,
    TO_CHAR(PREV_DAY,'YYYY-MM-DD')    AS PREV_DAY,
    (vd.t0 - PREV_DAY)               AS DAY_GAP,
    rn                              AS HISTORY_DAYS,
    -- T0 均线特征(不足历史长度置 NULL)
    ROUND(CASE WHEN rn>=5   THEN MA5   END, 3) AS MA5,
    ROUND(CASE WHEN rn>=10  THEN MA10  END, 3) AS MA10,
    ROUND(CASE WHEN rn>=20  THEN MA20  END, 3) AS MA20,
    ROUND(CASE WHEN rn>=60  THEN MA60  END, 3) AS MA60,
    ROUND(CASE WHEN rn>=120 THEN MA120 END, 3) AS MA120,
    ROUND(CASE WHEN rn>=250 THEN MA250 END, 3) AS MA250,
    -- T-1 均线特征(不足历史长度置 NULL)
    ROUND(CASE WHEN rn>=5   THEN PREV_MA5   END, 3) AS PREV_MA5,
    ROUND(CASE WHEN rn>=10  THEN PREV_MA10  END, 3) AS PREV_MA10,
    ROUND(CASE WHEN rn>=20  THEN PREV_MA20  END, 3) AS PREV_MA20,
    ROUND(CASE WHEN rn>=60  THEN PREV_MA60  END, 3) AS PREV_MA60,
    ROUND(CASE WHEN rn>=120 THEN PREV_MA120 END, 3) AS PREV_MA120,
    ROUND(CASE WHEN rn>=250 THEN PREV_MA250 END, 3) AS PREV_MA250,
    -- 中间标记(可解释性)
    CASE WHEN rn>=250
              AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
         THEN 1 ELSE 0 END AS ALIGN_T0,
    CASE WHEN rn>=250
              AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60
              AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
         THEN 1 ELSE 0 END AS ALIGN_T1,
    CASE WHEN rn>=250
              AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20
              AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
         THEN 1 ELSE 0 END AS ALL_UP,
    -- 综合标签
    CASE WHEN rn>=250
              AND (vd.t0 - PREV_DAY) <= 7
              AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
              AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60
              AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
              AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20
              AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
         THEN 1 ELSE 0 END AS LABEL
FROM lagged, vd
WHERE TRADINGDAY = vd.t0          -- 取 T0 当日快照(每只股票一行)
ORDER BY SECUCODE
;
