-- ============================================================
-- A股全市场「均线多头排列」特征矩阵 + 标签 (复权价格版 - 聚源 QT_DAILYQUOTE + QT_ADJUSTINGFACTOR)
-- 适用库: ZBJYDB (service JYDBTEST, Oracle 11g)
-- 时间语义: T0 = 最新交易日收盘; 仅用 T0 及历史数据, 无未来泄露
-- 复权逻辑: 基于聚源 RATIOADJUSTINGFACTOR 比例复权因子计算复权收盘价 ADJ_CLOSE
-- 产出: 每只A股一行(T0快照), 各均线(T0/T-1)为特征值, LABEL 为标签
-- ============================================================

WITH vd AS (
    -- 最新交易日 T0
    SELECT MAX(TRADINGDAY) AS t0 FROM ZBJYDB.QT_DAILYQUOTE
),
ashares AS (
    -- 仅筛选 A 股标的，关联公司代码 COMPANYCODE
    SELECT INNERCODE, COMPANYCODE, SECUCODE, COALESCE(SECUABBR, CHINAME) AS SECNAME
    FROM ZBJYDB.SECUMAIN
    WHERE SUBSTR(SECUCODE,1,2) IN ('60','68','00','30')
      AND SECUCATEGORY = 1
),
sw_ind AS (
    -- 聚源最新 2021 版申万行业分类 (STANDARD = 38)
    SELECT COMPANYCODE, FIRSTINDUSTRYNAME AS SW_IND1, SECONDINDUSTRYNAME AS SW_IND2
    FROM (
        SELECT COMPANYCODE, FIRSTINDUSTRYNAME, SECONDINDUSTRYNAME,
               ROW_NUMBER() OVER (PARTITION BY COMPANYCODE ORDER BY INFOPUBLDATE DESC, ID DESC) AS rk
        FROM ZBJYDB.LC_EXGINDUSTRY
        WHERE STANDARD = 38 AND CANCELDATE IS NULL
    ) WHERE rk = 1
),
init_fac AS (
    -- 取各A股在 (t0 - 400) 自然日之前最新的一条复权因子 (作为基准初始因子)
    SELECT INNERCODE, RATIOADJUSTINGFACTOR AS INIT_FACTOR
    FROM (
        SELECT AF.INNERCODE, AF.RATIOADJUSTINGFACTOR,
               ROW_NUMBER() OVER (PARTITION BY AF.INNERCODE ORDER BY AF.EXDIVIDATE DESC) AS rk
        FROM ZBJYDB.QT_ADJUSTINGFACTOR AF
        JOIN ashares S ON AF.INNERCODE = S.INNERCODE
        , vd
        WHERE AF.EXDIVIDATE < (vd.t0 - 400)
    ) WHERE rk = 1
),
daily_raw AS (
    -- 抽取 A 股日行情 (T0-400 至 T0)，并关联当天的除权因子
    SELECT 
        D.INNERCODE,
        S.SECUCODE,
        S.SECNAME,
        D.TRADINGDAY,
        D.CLOSEPRICE,
        AF.RATIOADJUSTINGFACTOR
    FROM ZBJYDB.QT_DAILYQUOTE D
    JOIN ashares S ON D.INNERCODE = S.INNERCODE
    LEFT JOIN ZBJYDB.QT_ADJUSTINGFACTOR AF 
      ON D.INNERCODE = AF.INNERCODE AND D.TRADINGDAY = AF.EXDIVIDATE
    , vd
    WHERE D.CLOSEPRICE IS NOT NULL
      AND D.TRADINGDAY <= vd.t0
      AND D.TRADINGDAY >= vd.t0 - 400
),
daily_adj AS (
    -- 向下填充复权因子并计算复权收盘价 ADJ_CLOSE
    SELECT
        r.INNERCODE,
        r.SECUCODE,
        r.SECNAME,
        r.TRADINGDAY,
        r.CLOSEPRICE,
        r.CLOSEPRICE * COALESCE(
            LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
            ),
            f.INIT_FACTOR,
            1.0
        ) AS ADJ_CLOSE
    FROM daily_raw r
    LEFT JOIN init_fac f ON r.INNERCODE = f.INNERCODE
),
ma AS (
    -- 逐只证券基于 ADJ_CLOSE 计算 6 条均线
    SELECT
        INNERCODE,
        SECUCODE,
        SECNAME,
        TRADINGDAY,
        CLOSEPRICE,
        ADJ_CLOSE,
        ROW_NUMBER() OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS rn,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS MA5,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS MA10,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS MA20,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS MA60,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120,
        AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS MA250
    FROM daily_adj
),
lagged AS (
    -- 取 T-1 (上一交易日) 的均线值 与 上一交易日日期
    SELECT
        m.*,
        LAG(MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA5,
        LAG(MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA10,
        LAG(MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA20,
        LAG(MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA60,
        LAG(MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA120,
        LAG(MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA250,
        LAG(TRADINGDAY) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_DAY
    FROM ma m
)
SELECT
    m.SECUCODE,
    m.SECNAME,
    COALESCE(I.SW_IND1, N'未分类') AS SW_IND1,
    COALESCE(I.SW_IND2, N'未分类') AS SW_IND2,
    TO_CHAR(m.TRADINGDAY,'YYYY-MM-DD') AS T0,
    TO_CHAR(PREV_DAY,'YYYY-MM-DD')    AS PREV_DAY,
    (vd.t0 - PREV_DAY)               AS DAY_GAP,
    rn                              AS HISTORY_DAYS,
    ROUND(CLOSEPRICE, 3)            AS CLOSEPRICE,
    ROUND(ADJ_CLOSE, 3)             AS ADJ_CLOSE,
    -- T0 均线特征(复权)
    ROUND(CASE WHEN rn>=5   THEN MA5   END, 3) AS MA5,
    ROUND(CASE WHEN rn>=10  THEN MA10  END, 3) AS MA10,
    ROUND(CASE WHEN rn>=20  THEN MA20  END, 3) AS MA20,
    ROUND(CASE WHEN rn>=60  THEN MA60  END, 3) AS MA60,
    ROUND(CASE WHEN rn>=120 THEN MA120 END, 3) AS MA120,
    ROUND(CASE WHEN rn>=250 THEN MA250 END, 3) AS MA250,
    -- T-1 均线特征(复权)
    ROUND(CASE WHEN rn>=5   THEN PREV_MA5   END, 3) AS PREV_MA5,
    ROUND(CASE WHEN rn>=10  THEN PREV_MA10  END, 3) AS PREV_MA10,
    ROUND(CASE WHEN rn>=20  THEN PREV_MA20  END, 3) AS PREV_MA20,
    ROUND(CASE WHEN rn>=60  THEN PREV_MA60  END, 3) AS PREV_MA60,
    ROUND(CASE WHEN rn>=120 THEN PREV_MA120 END, 3) AS PREV_MA120,
    ROUND(CASE WHEN rn>=250 THEN PREV_MA250 END, 3) AS PREV_MA250,
    -- 中间标记
    CASE WHEN rn>=250
              AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
         THEN 1 ELSE 0 END AS ALIGN_T0,
    CASE WHEN rn>=250
              AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60
              AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
         THEN 1 ELSE 0 END AS ALIGN_T1,
    CASE WHEN rn>=250
              AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20
              AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
         THEN 1 ELSE 0 END AS ALL_UP,
    -- 综合标签
    CASE WHEN rn>=250
              AND (vd.t0 - PREV_DAY) <= 7
              AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
              AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60
              AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
              AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20
              AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
         THEN 1 ELSE 0 END AS LABEL
FROM lagged m
JOIN ashares S ON m.INNERCODE = S.INNERCODE
LEFT JOIN sw_ind I ON S.COMPANYCODE = I.COMPANYCODE
, vd
WHERE m.TRADINGDAY = vd.t0
ORDER BY m.SECUCODE
