#!/usr/bin/env python3
"""
扩大到 30 只股票的 SQL vs Python 全口径多因子交叉验证
"""
import os
import oracledb
from test_factor_calc import compute_factors_py, get_db_conn

def test_30_stocks():
    conn = get_db_conn()
    cur = conn.cursor()

    # 抽取 30 只不同板块的活跃股票
    cur.execute("""
        SELECT SECUCODE FROM (
            SELECT SECUCODE FROM ZBJYDB.SECUMAIN
            WHERE SUBSTR(SECUCODE,1,2) IN ('60','68','00','30')
              AND SECUCATEGORY = 1
            ORDER BY INNERCODE ASC
        ) WHERE ROWNUM <= 30
    """)
    test_codes = [r[0] for r in cur.fetchall()]
    print(f"Testing 30 sample stocks: {test_codes}")

    codes_str = "'" + "','".join(test_codes) + "'"

    test_sql = f"""
    WITH ashares AS (
        SELECT INNERCODE, SECUCODE, COALESCE(SECUABBR, CHINAME) AS SECNAME
        FROM ZBJYDB.SECUMAIN
        WHERE SECUCODE IN ({codes_str})
          AND SECUCATEGORY = 1
    ),
    init_fac AS (
        SELECT INNERCODE, RATIOADJUSTINGFACTOR, ADJUSTINGFACTOR, ADJUSTINGCONST
        FROM (
            SELECT AF.INNERCODE, AF.RATIOADJUSTINGFACTOR, AF.ADJUSTINGFACTOR, AF.ADJUSTINGCONST,
                   ROW_NUMBER() OVER (PARTITION BY AF.INNERCODE ORDER BY AF.EXDIVIDATE DESC) AS rk
            FROM ZBJYDB.QT_ADJUSTINGFACTOR AF
            JOIN ashares S ON AF.INNERCODE = S.INNERCODE
            WHERE AF.EXDIVIDATE < (SYSDATE - 600)
        ) WHERE rk = 1
    ),
    daily_raw AS (
        SELECT 
            D.INNERCODE,
            S.SECUCODE,
            S.SECNAME,
            D.TRADINGDAY,
            D.OPENPRICE,
            D.HIGHPRICE,
            D.LOWPRICE,
            D.CLOSEPRICE,
            D.TURNOVERVALUE,
            AF.RATIOADJUSTINGFACTOR,
            AF.ADJUSTINGFACTOR,
            AF.ADJUSTINGCONST
        FROM ZBJYDB.QT_DAILYQUOTE D
        JOIN ashares S ON D.INNERCODE = S.INNERCODE
        LEFT JOIN ZBJYDB.QT_ADJUSTINGFACTOR AF 
          ON D.INNERCODE = AF.INNERCODE AND D.TRADINGDAY = AF.EXDIVIDATE
        WHERE D.CLOSEPRICE IS NOT NULL
          AND D.TRADINGDAY >= (SYSDATE - 600)
    ),
    daily_adj AS (
        SELECT
            r.INNERCODE,
            r.SECUCODE,
            r.SECNAME,
            r.TRADINGDAY,
            r.OPENPRICE,
            r.HIGHPRICE,
            r.LOWPRICE,
            r.CLOSEPRICE,
            r.TURNOVERVALUE,
            -- 比例复权因子与价格
            COALESCE(
                LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.RATIOADJUSTINGFACTOR,
                1.0
            ) AS RATIO_FAC,
            r.OPENPRICE * COALESCE(
                LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.RATIOADJUSTINGFACTOR,
                1.0
            ) AS RATIO_OPEN,
            r.HIGHPRICE * COALESCE(
                LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.RATIOADJUSTINGFACTOR,
                1.0
            ) AS RATIO_HIGH,
            r.LOWPRICE * COALESCE(
                LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.RATIOADJUSTINGFACTOR,
                1.0
            ) AS RATIO_LOW,
            r.CLOSEPRICE * COALESCE(
                LAST_VALUE(r.RATIOADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.RATIOADJUSTINGFACTOR,
                1.0
            ) AS ADJ_CLOSE,
            -- 精确复权
            r.OPENPRICE * COALESCE(
                LAST_VALUE(r.ADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGFACTOR,
                1.0
            ) + COALESCE(
                LAST_VALUE(r.ADJUSTINGCONST IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGCONST,
                0.0
            ) AS EXACT_OPEN,
            r.HIGHPRICE * COALESCE(
                LAST_VALUE(r.ADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGFACTOR,
                1.0
            ) + COALESCE(
                LAST_VALUE(r.ADJUSTINGCONST IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGCONST,
                0.0
            ) AS EXACT_HIGH,
            r.LOWPRICE * COALESCE(
                LAST_VALUE(r.ADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGFACTOR,
                1.0
            ) + COALESCE(
                LAST_VALUE(r.ADJUSTINGCONST IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGCONST,
                0.0
            ) AS EXACT_LOW,
            r.CLOSEPRICE * COALESCE(
                LAST_VALUE(r.ADJUSTINGFACTOR IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGFACTOR,
                1.0
            ) + COALESCE(
                LAST_VALUE(r.ADJUSTINGCONST IGNORE NULLS) OVER (
                    PARTITION BY r.INNERCODE ORDER BY r.TRADINGDAY
                ),
                f.ADJUSTINGCONST,
                0.0
            ) AS EXACT_CLOSE,
            -- 红绿
            CASE WHEN r.CLOSEPRICE > r.OPENPRICE THEN 1 ELSE 0 END AS IS_RED,
            CASE WHEN r.CLOSEPRICE < r.OPENPRICE THEN 1 ELSE 0 END AS IS_GREEN
        FROM daily_raw r
        LEFT JOIN init_fac f ON r.INNERCODE = f.INNERCODE
    ),
    window_stats AS (
        SELECT
            d.*,
            ROW_NUMBER() OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS rn,
            -- 比例复权均线
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS MA5,
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS MA10,
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS MA20,
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS MA60,
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120,
            AVG(ADJ_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS MA250,
            -- 原始均线
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS RAW_MA5,
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS RAW_MA10,
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS RAW_MA20,
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS RAW_MA60,
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS RAW_MA120,
            AVG(CLOSEPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS RAW_MA250,
            -- 精确复权均线
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   4 PRECEDING AND CURRENT ROW) AS EXACT_MA5,
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN   9 PRECEDING AND CURRENT ROW) AS EXACT_MA10,
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  19 PRECEDING AND CURRENT ROW) AS EXACT_MA20,
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN  59 PRECEDING AND CURRENT ROW) AS EXACT_MA60,
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS EXACT_MA120,
            AVG(EXACT_CLOSE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 249 PRECEDING AND CURRENT ROW) AS EXACT_MA250,
            -- HL+5R 窗口 (ratio / raw / exact):
            MIN(RATIO_LOW)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS RECENT_LOW_10,
            MAX(RATIO_HIGH) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 169 PRECEDING AND CURRENT ROW) AS WIN_HIGH_170,
            MIN(RATIO_LOW)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS WIN_LOW_30,

            MIN(LOWPRICE)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS RAW_RECENT_LOW_10,
            MAX(HIGHPRICE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 169 PRECEDING AND CURRENT ROW) AS RAW_WIN_HIGH_170,
            MIN(LOWPRICE)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS RAW_WIN_LOW_30,

            MIN(EXACT_LOW)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) AS EXACT_RECENT_LOW_10,
            MAX(EXACT_HIGH) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 169 PRECEDING AND CURRENT ROW) AS EXACT_WIN_HIGH_170,
            MIN(EXACT_LOW)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS EXACT_WIN_LOW_30,

            -- HL+AMO 窗口:
            MAX(RATIO_HIGH) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 179 PRECEDING AND CURRENT ROW) AS WIN_HIGH_180,
            MAX(HIGHPRICE)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 179 PRECEDING AND CURRENT ROW) AS RAW_WIN_HIGH_180,
            MAX(EXACT_HIGH) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 179 PRECEDING AND CURRENT ROW) AS EXACT_WIN_HIGH_180,

            -- AMO 窗口:
            MAX(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 14 PRECEDING AND CURRENT ROW) AS WIN_MAX_15,
            AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)  AS WIN_AVG_5,
            AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 9 PRECEDING AND CURRENT ROW)  AS WIN_AVG_10,
            AVG(TURNOVERVALUE) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY ROWS BETWEEN 14 PRECEDING AND CURRENT ROW) AS WIN_AVG_15
        FROM daily_adj d
    ),
    lagged AS (
        SELECT
            w.*,
            -- 均线 LAG (ratio)
            LAG(MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA5,
            LAG(MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA10,
            LAG(MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA20,
            LAG(MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA60,
            LAG(MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA120,
            LAG(MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_MA250,
            -- 均线 LAG (raw)
            LAG(RAW_MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA5,
            LAG(RAW_MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA10,
            LAG(RAW_MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA20,
            LAG(RAW_MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA60,
            LAG(RAW_MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA120,
            LAG(RAW_MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_RAW_MA250,
            -- 均线 LAG (exact)
            LAG(EXACT_MA5)   OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA5,
            LAG(EXACT_MA10)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA10,
            LAG(EXACT_MA20)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA20,
            LAG(EXACT_MA60)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA60,
            LAG(EXACT_MA120) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA120,
            LAG(EXACT_MA250) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_EXACT_MA250,

            LAG(TRADINGDAY) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PREV_DAY,

            -- 红绿 LAG
            LAG(IS_RED, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T1,
            LAG(IS_RED, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T2,
            LAG(IS_RED, 3) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T3,
            LAG(IS_RED, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RED_T4,
            LAG(IS_GREEN, 5) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS GREEN_T5,

            -- HL+5R LAGs (ratio)
            LAG(RATIO_OPEN, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RATIO_OPEN_T4,
            LAG(WIN_HIGH_170, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_HIGH_170,
            LAG(WIN_LOW_30, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_LOW_30,

            -- HL+5R LAGs (raw)
            LAG(OPENPRICE, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_OPEN_T4,
            LAG(RAW_WIN_HIGH_170, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_PRIOR_HIGH_170,
            LAG(RAW_WIN_LOW_30, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_PRIOR_LOW_30,

            -- HL+5R LAGs (exact)
            LAG(EXACT_OPEN, 4) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_OPEN_T4,
            LAG(EXACT_WIN_HIGH_170, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_PRIOR_HIGH_170,
            LAG(EXACT_WIN_LOW_30, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_PRIOR_LOW_30,

            -- AMO LAGs
            LAG(TURNOVERVALUE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AMT_1,
            LAG(WIN_MAX_15, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS MAX_15,
            LAG(WIN_AVG_5, 1)  OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_5,
            LAG(WIN_AVG_10, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_10,
            LAG(WIN_AVG_15, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS AVG_15,
            LAG(ADJ_CLOSE, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS ADJ_CLOSE_T10,
            LAG(CLOSEPRICE, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_CLOSE_T10,
            LAG(EXACT_CLOSE, 10) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_CLOSE_T10,

            -- HL+AMO LAGs
            LAG(ADJ_CLOSE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS ADJ_CLOSE_T1,
            LAG(CLOSEPRICE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_CLOSE_T1,
            LAG(EXACT_CLOSE, 1) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_CLOSE_T1,
            LAG(WIN_HIGH_180, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS PRIOR_HIGH_180,
            LAG(RAW_WIN_HIGH_180, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS RAW_PRIOR_HIGH_180,
            LAG(EXACT_WIN_HIGH_180, 2) OVER (PARTITION BY INNERCODE ORDER BY TRADINGDAY) AS EXACT_PRIOR_HIGH_180
        FROM window_stats w
    ),
    calculated AS (
        SELECT
            l.*,
            -- 5日连红标记
            CASE WHEN IS_RED = 1 AND RED_T1 = 1 AND RED_T2 = 1 AND RED_T3 = 1 AND RED_T4 = 1 THEN 1 ELSE 0 END AS RED_5,

            -- HL+5R 中间指标 (ratio)
            CASE WHEN PRIOR_HIGH_170 > 0 THEN 1.0 - RECENT_LOW_10 / PRIOR_HIGH_170 ELSE 0 END AS DRAWDOWN_180,
            CASE WHEN PRIOR_LOW_30 > 0 THEN RECENT_LOW_10 / PRIOR_LOW_30 - 1.0 ELSE 0 END AS LOW_REBOUND_30,
            CASE WHEN RATIO_OPEN_T4 > 0 THEN ADJ_CLOSE / RATIO_OPEN_T4 - 1.0 ELSE 0 END AS FIVE_DAY_GAIN,

            -- HL+5R 中间指标 (raw)
            CASE WHEN RAW_PRIOR_HIGH_170 > 0 THEN 1.0 - RAW_RECENT_LOW_10 / RAW_PRIOR_HIGH_170 ELSE 0 END AS RAW_DRAWDOWN_180,
            CASE WHEN RAW_PRIOR_LOW_30 > 0 THEN RAW_RECENT_LOW_10 / RAW_PRIOR_LOW_30 - 1.0 ELSE 0 END AS RAW_LOW_REBOUND_30,
            CASE WHEN RAW_OPEN_T4 > 0 THEN CLOSEPRICE / RAW_OPEN_T4 - 1.0 ELSE 0 END AS RAW_FIVE_DAY_GAIN,

            -- HL+5R 中间指标 (exact)
            CASE WHEN EXACT_PRIOR_HIGH_170 > 0 THEN 1.0 - EXACT_RECENT_LOW_10 / EXACT_PRIOR_HIGH_170 ELSE 0 END AS EXACT_DRAWDOWN_180,
            CASE WHEN EXACT_PRIOR_LOW_30 > 0 THEN EXACT_RECENT_LOW_10 / EXACT_PRIOR_LOW_30 - 1.0 ELSE 0 END AS EXACT_LOW_REBOUND_30,
            CASE WHEN EXACT_OPEN_T4 > 0 THEN EXACT_CLOSE / EXACT_OPEN_T4 - 1.0 ELSE 0 END AS EXACT_FIVE_DAY_GAIN,

            -- AMO 中间指标
            CASE WHEN ADJ_CLOSE_T10 > 0 THEN ADJ_CLOSE / ADJ_CLOSE_T10 - 1.0 ELSE 0 END AS RETURN_10,
            CASE WHEN RAW_CLOSE_T10 > 0 THEN CLOSEPRICE / RAW_CLOSE_T10 - 1.0 ELSE 0 END AS RAW_RETURN_10,
            CASE WHEN EXACT_CLOSE_T10 > 0 THEN EXACT_CLOSE / EXACT_CLOSE_T10 - 1.0 ELSE 0 END AS EXACT_RETURN_10,

            -- HL+AMO 中间指标
            CASE WHEN PRIOR_HIGH_180 > 0 THEN 1.0 - ADJ_CLOSE_T1 / PRIOR_HIGH_180 ELSE 0 END AS PREV_DRAWDOWN_180,
            CASE WHEN RAW_PRIOR_HIGH_180 > 0 THEN 1.0 - RAW_CLOSE_T1 / RAW_PRIOR_HIGH_180 ELSE 0 END AS RAW_PREV_DRAWDOWN_180,
            CASE WHEN EXACT_PRIOR_HIGH_180 > 0 THEN 1.0 - EXACT_CLOSE_T1 / EXACT_PRIOR_HIGH_180 ELSE 0 END AS EXACT_PREV_DRAWDOWN_180
        FROM lagged l
    )
    SELECT
        SECUCODE,
        SECNAME,
        TO_CHAR(TRADINGDAY, 'YYYY-MM-DD') AS T0,
        TO_CHAR(PREV_DAY, 'YYYY-MM-DD') AS PREV_DAY,
        (TRADINGDAY - PREV_DAY) AS DAY_GAP,
        rn AS HISTORY_DAYS,
        ROUND(CLOSEPRICE, 3) AS CLOSEPRICE,
        ROUND(ADJ_CLOSE, 3) AS ADJ_CLOSE,
        ROUND(EXACT_CLOSE, 3) AS EXACT_CLOSE,
        ROUND(TURNOVERVALUE, 0) AS TURNOVERVALUE,

        -- 均线 (ratio)
        ROUND(CASE WHEN rn>=5   THEN MA5   END, 3) AS MA5,
        ROUND(CASE WHEN rn>=10  THEN MA10  END, 3) AS MA10,
        ROUND(CASE WHEN rn>=20  THEN MA20  END, 3) AS MA20,
        ROUND(CASE WHEN rn>=60  THEN MA60  END, 3) AS MA60,
        ROUND(CASE WHEN rn>=120 THEN MA120 END, 3) AS MA120,
        ROUND(CASE WHEN rn>=250 THEN MA250 END, 3) AS MA250,
        ROUND(CASE WHEN rn>=5   THEN PREV_MA5   END, 3) AS PREV_MA5,
        ROUND(CASE WHEN rn>=10  THEN PREV_MA10  END, 3) AS PREV_MA10,
        ROUND(CASE WHEN rn>=20  THEN PREV_MA20  END, 3) AS PREV_MA20,
        ROUND(CASE WHEN rn>=60  THEN PREV_MA60  END, 3) AS PREV_MA60,
        ROUND(CASE WHEN rn>=120 THEN PREV_MA120 END, 3) AS PREV_MA120,
        ROUND(CASE WHEN rn>=250 THEN PREV_MA250 END, 3) AS PREV_MA250,

        CASE WHEN rn>=250 AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250 THEN 1 ELSE 0 END AS ALIGN_T0,
        CASE WHEN rn>=250 AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60 AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250 THEN 1 ELSE 0 END AS ALIGN_T1,
        CASE WHEN rn>=250 AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20 AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250 THEN 1 ELSE 0 END AS ALL_UP,
        CASE WHEN rn>=250 AND (TRADINGDAY - PREV_DAY) <= 7
                  AND MA5>MA10 AND MA10>MA20 AND MA20>MA60 AND MA60>MA120 AND MA120>MA250
                  AND PREV_MA5>PREV_MA10 AND PREV_MA10>PREV_MA20 AND PREV_MA20>PREV_MA60 AND PREV_MA60>PREV_MA120 AND PREV_MA120>PREV_MA250
                  AND MA5>PREV_MA5 AND MA10>PREV_MA10 AND MA20>PREV_MA20 AND MA60>PREV_MA60 AND MA120>PREV_MA120 AND MA250>PREV_MA250
             THEN 1 ELSE 0 END AS LABEL,

        -- 生产主口径因子标签 (ratio)
        CASE WHEN rn >= 180 AND DRAWDOWN_180 > 0.25 AND LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND FIVE_DAY_GAIN < 0.13 THEN 1 ELSE 0 END AS FACTOR_HL_5R,
        CASE WHEN rn >= 6 AND RED_5 = 1 AND GREEN_T5 = 1 AND NOT (rn >= 180 AND DRAWDOWN_180 > 0.25 AND LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND FIVE_DAY_GAIN < 0.13) THEN 1 ELSE 0 END AS FACTOR_5R,
        CASE WHEN rn >= 16 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND RETURN_10 < 0.50 THEN 1 ELSE 0 END AS FACTOR_AMO,
        CASE WHEN rn >= 182 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND RETURN_10 < 0.50 AND PREV_DRAWDOWN_180 > 0.25 THEN 1 ELSE 0 END AS FACTOR_HL_AMO,

        -- 原始价对照因子标签 (raw)
        CASE WHEN rn >= 180 AND RAW_DRAWDOWN_180 > 0.25 AND RAW_LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND RAW_FIVE_DAY_GAIN < 0.13 THEN 1 ELSE 0 END AS RAW_FACTOR_HL_5R,
        CASE WHEN rn >= 6 AND RED_5 = 1 AND GREEN_T5 = 1 AND NOT (rn >= 180 AND RAW_DRAWDOWN_180 > 0.25 AND RAW_LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND RAW_FIVE_DAY_GAIN < 0.13) THEN 1 ELSE 0 END AS RAW_FACTOR_5R,
        CASE WHEN rn >= 16 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND RAW_RETURN_10 < 0.50 THEN 1 ELSE 0 END AS RAW_FACTOR_AMO,
        CASE WHEN rn >= 182 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND RAW_RETURN_10 < 0.50 AND RAW_PREV_DRAWDOWN_180 > 0.25 THEN 1 ELSE 0 END AS RAW_FACTOR_HL_AMO,

        -- 精确复权对照因子标签 (exact)
        CASE WHEN rn >= 180 AND EXACT_DRAWDOWN_180 > 0.25 AND EXACT_LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND EXACT_FIVE_DAY_GAIN < 0.13 THEN 1 ELSE 0 END AS EXACT_FACTOR_HL_5R,
        CASE WHEN rn >= 6 AND RED_5 = 1 AND GREEN_T5 = 1 AND NOT (rn >= 180 AND EXACT_DRAWDOWN_180 > 0.25 AND EXACT_LOW_REBOUND_30 < 0.10 AND RED_5 = 1 AND EXACT_FIVE_DAY_GAIN < 0.13) THEN 1 ELSE 0 END AS EXACT_FACTOR_5R,
        CASE WHEN rn >= 16 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND EXACT_RETURN_10 < 0.50 THEN 1 ELSE 0 END AS EXACT_FACTOR_AMO,
        CASE WHEN rn >= 182 AND TURNOVERVALUE > 100000000.0 AND TURNOVERVALUE > 1.2 * MAX_15 AND TURNOVERVALUE > 1.8 * AMT_1 AND TURNOVERVALUE > 1.8 * AVG_5 AND TURNOVERVALUE > 1.8 * AVG_10 AND TURNOVERVALUE > 1.8 * AVG_15 AND IS_RED = 1 AND EXACT_RETURN_10 < 0.50 AND EXACT_PREV_DRAWDOWN_180 > 0.25 THEN 1 ELSE 0 END AS EXACT_FACTOR_HL_AMO,

        -- 详细指标输出 (用于前端明细展示与复核)
        ROUND(DRAWDOWN_180 * 100, 2) AS DRAWDOWN_180_PCT,
        ROUND(LOW_REBOUND_30 * 100, 2) AS LOW_REBOUND_30_PCT,
        ROUND(FIVE_DAY_GAIN * 100, 2) AS FIVE_DAY_GAIN_PCT,
        ROUND(RETURN_10 * 100, 2) AS RETURN_10_PCT,
        ROUND(PREV_DRAWDOWN_180 * 100, 2) AS PREV_DRAWDOWN_180_PCT,
        ROUND(TURNOVERVALUE / NULLIF(AMT_1, 0), 2) AS AMT_RATIO_PREV,
        ROUND(TURNOVERVALUE / NULLIF(AVG_5, 0), 2) AS AMT_RATIO_MA5,
        ROUND(TURNOVERVALUE / NULLIF(AVG_10, 0), 2) AS AMT_RATIO_MA10,
        ROUND(TURNOVERVALUE / NULLIF(AVG_15, 0), 2) AS AMT_RATIO_MA15,
        ROUND(TURNOVERVALUE / NULLIF(MAX_15, 0), 2) AS AMT_RATIO_MAX15
    FROM calculated
    ORDER BY TRADINGDAY ASC
    """

    print("Executing 30 stocks SQL test...")
    cur.execute(test_sql)
    sql_cols = [c[0] for c in cur.description]
    sql_rows = [dict(zip(sql_cols, r)) for r in cur.fetchall()]
    print(f"SQL returned {len(sql_rows)} rows across 30 stocks.")

    from collections import defaultdict
    by_stock_sql = defaultdict(list)
    for r in sql_rows:
        by_stock_sql[r["SECUCODE"]].append(r)

    total_compared = 0
    mismatch_count = 0

    for code in test_codes:
        if code not in by_stock_sql:
            continue
        cur.execute("""
            SELECT RATIOADJUSTINGFACTOR, ADJUSTINGFACTOR, ADJUSTINGCONST
            FROM (
                SELECT AF.RATIOADJUSTINGFACTOR, AF.ADJUSTINGFACTOR, AF.ADJUSTINGCONST
                FROM ZBJYDB.QT_ADJUSTINGFACTOR AF
                JOIN ZBJYDB.SECUMAIN S ON AF.INNERCODE = S.INNERCODE
                WHERE S.SECUCODE = :code AND S.SECUCATEGORY = 1
                  AND AF.EXDIVIDATE < (SYSDATE - 600)
                ORDER BY AF.EXDIVIDATE DESC
            ) WHERE ROWNUM = 1
        """, code=code)
        init_row = cur.fetchone()
        init_ratio = float(init_row[0]) if (init_row and init_row[0] is not None) else 1.0
        init_adj_f = float(init_row[1]) if (init_row and init_row[1] is not None) else 1.0
        init_adj_c = float(init_row[2]) if (init_row and init_row[2] is not None) else 0.0

        cur.execute("""
            SELECT 
                D.TRADINGDAY,
                D.OPENPRICE,
                D.HIGHPRICE,
                D.LOWPRICE,
                D.CLOSEPRICE,
                D.TURNOVERVALUE,
                AF.RATIOADJUSTINGFACTOR,
                AF.ADJUSTINGFACTOR,
                AF.ADJUSTINGCONST
            FROM ZBJYDB.QT_DAILYQUOTE D
            JOIN ZBJYDB.SECUMAIN S ON D.INNERCODE = S.INNERCODE
            LEFT JOIN ZBJYDB.QT_ADJUSTINGFACTOR AF
              ON D.INNERCODE = AF.INNERCODE AND D.TRADINGDAY = AF.EXDIVIDATE
            WHERE S.SECUCODE = :code
              AND S.SECUCATEGORY = 1
              AND D.CLOSEPRICE IS NOT NULL
              AND D.TRADINGDAY >= (SYSDATE - 600)
            ORDER BY D.TRADINGDAY ASC
        """, code=code)
        raw_cols = [c[0] for c in cur.description]
        py_raw_rows = [dict(zip(raw_cols, r)) for r in cur.fetchall()]
        py_res = compute_factors_py(py_raw_rows, init_ratio=init_ratio, init_adj_f=init_adj_f, init_adj_c=init_adj_c)

        sql_data = by_stock_sql[code]
        assert len(sql_data) == len(py_res), f"Row count mismatch for {code}: SQL {len(sql_data)} vs Py {len(py_res)}"

        for s_row, p_row in zip(sql_data, py_res):
            total_compared += 1
            date_s = s_row["T0"]
            date_p = p_row["date"]
            assert date_s == date_p, f"Date mismatch: {date_s} vs {date_p}"

            # 主口径
            for f_key, s_key in [("factor_5r", "FACTOR_5R"), ("factor_hl_5r", "FACTOR_HL_5R"),
                                 ("factor_amo", "FACTOR_AMO"), ("factor_hl_amo", "FACTOR_HL_AMO"),
                                 ("raw_factor_5r", "RAW_FACTOR_5R"), ("raw_factor_hl_5r", "RAW_FACTOR_HL_5R"),
                                 ("raw_factor_amo", "RAW_FACTOR_AMO"), ("raw_factor_hl_amo", "RAW_FACTOR_HL_AMO"),
                                 ("exact_factor_5r", "EXACT_FACTOR_5R"), ("exact_factor_hl_5r", "EXACT_FACTOR_HL_5R"),
                                 ("exact_factor_amo", "EXACT_FACTOR_AMO"), ("exact_factor_hl_amo", "EXACT_FACTOR_HL_AMO")]:
                if s_row[s_key] != p_row[f_key]:
                    print(f"MISMATCH {s_key} for {code} on {date_s}: SQL={s_row[s_key]} Py={p_row[f_key]}")
                    mismatch_count += 1

    print(f"\n[30 Stocks Comparison Completed] Total compared: {total_compared} rows x 12 factor keys. Mismatches: {mismatch_count}")
    assert mismatch_count == 0, f"Found {mismatch_count} mismatches in 30 stocks test!"
    print("[ALL 30 STOCKS PASSED] 100% Exact Match across all 3 price modes and 4 factors!")
    conn.close()

if __name__ == "__main__":
    test_30_stocks()
